# Generated by Django 5.1.1 on 2024-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_facility_order_trip_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='facilities',
            field=models.ManyToManyField(related_name='buses', to='station.facility'),
        ),
    ]
