# Generated by Django 5.1.1 on 2024-09-12 21:10

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_bus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.bus_image_path),
        ),
    ]
